### ISSUE TITLE
GitBook help

### ISSUE THREAD

**Issue by AaronO** [jadijadi/lpic1book#1]
Hi @jadijadi it's Aaron here from the GitBook team.

I've cloned your book's git repo locally from our servers. Could you give me (temporary) push access to this repo ?

That way I'll push here and since you already setup GitHub integration (https://www.gitbook.com/book/jadi/lpic1/settings/github), everything should work nicely from there.

You will still be able to use our web editor (it does require `https`, maybe that's blocked too). But you will at least be able to push over `ssh` to this GitHub repo which will send us WebHook events triggering the builds for you.

**Comment by AaronO** [comment]
@jadijadi It should be good now :)

Let me know if there's anything else that I can do to help !

**P.S:** Feel free to remove my push access too

**Comment by jadijadi** [comment]
@AaronO 

Thank you very much for the fast / bold / helpful and encouraging response. I initially resolved my problem by configuring an anti-filter (socks proxy) and attaching it to a proxy running on my machine on port 8080 and proxying my ssh session from there. 

But your help makes it much more easier. Thank you and this made my day :)

Jadi

**Comment by AaronO** [comment]
@jadijadi No problem, we're always more than happy to help !

In your specific case, it's rather sad/unfortunate that you need to jump through all those hoops just to do normal things (I'm not a big fan of government filtering/censorship).

By the way, your book looks pretty cool ! I'm a big fan of systems programming (I spend a lot of time building our backend stuff). And @SamyPesse (my co-founder) wrote a nice GitBook: https://github.com/SamyPesse/How-to-Make-a-Computer-Operating-System.

We're thinking of doing a page that showcases some great developer GitBooks (like `library.gitbook.com`), I think it would be nice to have a "system" section (about low-level, kernel stuff, etc ...), when we do it seems like your book would be a great fit !

Best of luck with your book !

**P.S:** In the future you can email me at `aaron@gitbook.com` if you need any help or want to share feedback/ideas.

**Comment by jadijadi** [comment]
Thank you again for all the help. I'll be more than glad to be part of your showcase.
We'll be in touch and you can reach me on www.jadi.ir / jadijadi@gmail.com.
Yours
Jadi
