### ISSUE TITLE
Link to videos is missing

### ISSUE THREAD

**Issue by emadpres** [jadijadi/lpic1book#17]
Can you please provide the link to Persian videos?

The `README` file claims there is such a link, but I can't find any relevant link:
> If you want to download Farsi LPIC 101 & LPIC 102 exam videos use this torrent magnet link

**Comment by jadijadi** [comment]
Sorry that I have not answered this in time. you can find the lpic videos on my youtoube channel youtube.com/jadimirmirani but I'm starting to record the new version and will embed in the middle of these videos.
