### ISSUE TITLE
Backup files are tracked for this repo?

### ISSUE THREAD

**Issue by ypid** [jadijadi/lpic1book#2]
Hi

Thanks for the document. Any reason for tracking all the backup files that end with a tilde?

* [1011_determine_and_configure_hardware_settings.md~](https://github.com/jadijadi/lpic1book/blob/master/1011_determine_and_configure_hardware_settings.md~)

**Comment by jadijadi** [comment]
My mistake. Thanks for pointing it. Will add a .gitignore
By the way the main output is on gitbooks. http://j.mp/jadilpic1
